### ISSUE TITLE
ERROR: failed to set programming file

### ISSUE THREAD

**Issue by eliquinox** [fyquah95/hardcaml_arty#7]
Following all the README instructions, I get the following error running `djtgcfg prog --file outputs/hardcaml_arty_top.bit -d Arty -i 0`:

```
ERROR: failed to set programming file
```

`djtgcfg enum` output:

```
Found 1 device(s)

Device: Arty
    Device Transport Type: 00020001 (USB)
    Product Name:          Digilent Arty A7-100T
    User Name:             Arty
    Serial Number:         210319B57CCD
```

What could be causing this?

**Comment by andrewray** [comment]
The example projects target the Arty A7-35T.  Did you update the scripts for the A7-100T (specifically synth.tcl)?  Probably also need to add a new board definition to examples/blinker/boards

**Comment by eliquinox** [comment]
@andrewray thank you very much. That was it - wrong assumption on my end. Fixed by:

1.  copying the contents of https://github.com/Digilent/vivado-boards/tree/master/new/board_files/arty-a7-100 folder into `boards` folder in blinker project.
2. Changing first few lines in `synth.tcl`:
```
create_project -in_memory -part xc7a100tcsg324-1
set_property board_part digilentinc.com:arty-a7-100:part0:1.0 [current_project]
```

Now there is a bit of a disco going on at my desk :)

**Comment by eliquinox** [comment]
Let me know if you want blinker project to support Arty A7-100T - happy to PR my changes.

**Comment by andrewray** [comment]
That would be awesome.

**Comment by eliquinox** [comment]
@andrewray here it is: https://github.com/fyquah/hardcaml_arty/pull/8
